language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - PEEWEE_TEST_BACKEND=sqlite
  - PEEWEE_TEST_BACKEND=postgresql
  - PEEWEE_TEST_BACKEND=mysql
addons:
  postgresql: "9.4"
services:
  - postgresql
  - mysql
install:
  - pip install psycopg2 pymysql
  - pip install --install-option="--no-cython-compile" https://github.com/cython/cython/archive/20256403e4d81b7eea1165bf78b8faf8502e8204.zip
before_script:
  - sh -c "python setup.py build_ext -i"
  - sh -c "psql -c 'drop database if exists peewee_test;' -U postgres"
  - sh -c "psql -c 'create database peewee_test;' -U postgres"
  - sh -c "psql peewee_test -c 'create extension hstore;' -U postgres"
  - sh -c "mysql -e 'drop database if exists peewee_test;'"
  - sh -c "mysql -e 'create database peewee_test;'"
script: "python runtests.py -a"
